### ISSUE TITLE
Errors regarding the model code.

### ISSUE THREAD

**Issue by Soham0979** [GeorgKindermann/g4m#3]
![Screenshot from 2023-11-29 16-45-24](https://github.com/GeorgKindermann/g4m/assets/124671345/a478d619-5fd2-4710-be76-bd6e3cfedbfd)
![Screenshot from 2023-11-29 16-46-05](https://github.com/GeorgKindermann/g4m/assets/124671345/2a34848d-e261-4798-8216-c9a9001acfb9)
![Screenshot from 2023-11-29 16-46-20](https://github.com/GeorgKindermann/g4m/assets/124671345/263b8b89-081a-4cf1-a39e-ead4968ac396)

These are the errors and warnings that are show when you run make from parent directory that is the g4m-master directory.

**Comment by GeorgKindermann** [comment]
Made some fixes to remove the errors. Hope it works now.
